#!/bin/sh

# Suppress kernel messages
dmesg -n 1
clear

# Create directories
mkdir -p home/msmd
mkdir -p dev
mkdir -p proc
mkdir -p sys

# Mount file systems
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

# Set permissions
chown root:root / /bin/sudo /etc/sudoers
chmod 0440 /etc/sudoers
chmod +s /bin/sudo
chown -R msmd:staff /home /tmp
chmod -R a+x /home /tmp

# Start buxybox init as PID 1
exec /sbin/init
