#!/bin/sh

# Suppress kernel messages
dmesg -n 1
clear && cat /etc/logo.txt

# Mount file systems
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

# Create default group & user
echo "staff:x:1001:" > /etc/group
echo "msmd:x:1001:1001:msmd:/home/msmd:/etc/shell.sh" > /etc/passwd
chown -R msmd:staff /home
chmod -R a+x /home 

# Setup networking
for NETDEV in /sys/class/net/* ; do
  ip link set ${NETDEV##*/} up
  [ ${NETDEV##*/} != lo ] && udhcpc -b -i ${NETDEV##*/} -s /etc/network.sh
done

# Start buxybox init as PID 1
exec /sbin/init
