#!/bin/sh

# Suppress kernel messages
dmesg -n 1

# Display logo

# Mount file systems
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

# Setup networking
for NETDEV in /sys/class/net/* ; do
  clear && cat /etc/logo.txt
  echo "Found network device ${NETDEV##*/}"
  ip link set ${NETDEV##*/} up
  [ ${NETDEV##*/} != lo ] && udhcpc -b -i ${NETDEV##*/} -s /etc/network.sh
done

# Start buxybox init as PID 1
exec /sbin/init
